name: magnet
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
  - HCC
dependencies:
  - python=3.8.5
  - lightgbm=3.0.0
  - loguru=0.5.0
  - pandas=1.1.2
  - pytest=6.0.2
  - python-dotenv=0.14.0
  - pytorch=1.7.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - typer=0.3.1=py_0
  - cloudpickle=1.3.0
  - pytorch-lightning=1.1.2
  - numpy=1.18.5
  - matplotlib
  - feather-format
  - click
  - joblib
  - tqdm
  - mlflow
  - pyyaml
